# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Account(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Account()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAccount(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Account
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Account
    def Accountid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Account
    def Balance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Account
    def Frozen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def AccountStart(builder):
    builder.StartObject(3)

def Start(builder):
    AccountStart(builder)

def AccountAddAccountid(builder, accountid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(accountid), 0)

def AddAccountid(builder, accountid):
    AccountAddAccountid(builder, accountid)

def AccountAddBalance(builder, balance):
    builder.PrependFloat32Slot(1, balance, 0.0)

def AddBalance(builder, balance):
    AccountAddBalance(builder, balance)

def AccountAddFrozen(builder, frozen):
    builder.PrependFloat32Slot(2, frozen, 0.0)

def AddFrozen(builder, frozen):
    AccountAddFrozen(builder, frozen)

def AccountEnd(builder):
    return builder.EndObject()

def End(builder):
    return AccountEnd(builder)
