# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Bar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bar()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBar(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bar
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Bar
    def Exchange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Bar
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Bar
    def LastPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bar
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Bar
    def Amount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bar
    def OpenPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bar
    def HighPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bar
    def LowPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bar
    def ClosePrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BarStart(builder):
    builder.StartObject(10)

def Start(builder):
    BarStart(builder)

def BarAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    BarAddSymbol(builder, symbol)

def BarAddExchange(builder, exchange):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(exchange), 0)

def AddExchange(builder, exchange):
    BarAddExchange(builder, exchange)

def BarAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(2, timestamp, 0)

def AddTimestamp(builder, timestamp):
    BarAddTimestamp(builder, timestamp)

def BarAddLastPrice(builder, lastPrice):
    builder.PrependFloat32Slot(3, lastPrice, 0.0)

def AddLastPrice(builder, lastPrice):
    BarAddLastPrice(builder, lastPrice)

def BarAddVolume(builder, volume):
    builder.PrependInt32Slot(4, volume, 0)

def AddVolume(builder, volume):
    BarAddVolume(builder, volume)

def BarAddAmount(builder, amount):
    builder.PrependFloat32Slot(5, amount, 0.0)

def AddAmount(builder, amount):
    BarAddAmount(builder, amount)

def BarAddOpenPrice(builder, openPrice):
    builder.PrependFloat32Slot(6, openPrice, 0.0)

def AddOpenPrice(builder, openPrice):
    BarAddOpenPrice(builder, openPrice)

def BarAddHighPrice(builder, highPrice):
    builder.PrependFloat32Slot(7, highPrice, 0.0)

def AddHighPrice(builder, highPrice):
    BarAddHighPrice(builder, highPrice)

def BarAddLowPrice(builder, lowPrice):
    builder.PrependFloat32Slot(8, lowPrice, 0.0)

def AddLowPrice(builder, lowPrice):
    BarAddLowPrice(builder, lowPrice)

def BarAddClosePrice(builder, closePrice):
    builder.PrependFloat32Slot(9, closePrice, 0.0)

def AddClosePrice(builder, closePrice):
    BarAddClosePrice(builder, closePrice)

def BarEnd(builder):
    return builder.EndObject()

def End(builder):
    return BarEnd(builder)
