# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Position(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Position()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPosition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Position
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Position
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Position
    def Exchange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Position
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Position
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def Frozen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def Pnl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def TodayVolume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def TodayPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PositionStart(builder):
    builder.StartObject(9)

def Start(builder):
    PositionStart(builder)

def PositionAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    PositionAddSymbol(builder, symbol)

def PositionAddExchange(builder, exchange):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(exchange), 0)

def AddExchange(builder, exchange):
    PositionAddExchange(builder, exchange)

def PositionAddDirection(builder, direction):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(direction), 0)

def AddDirection(builder, direction):
    PositionAddDirection(builder, direction)

def PositionAddVolume(builder, volume):
    builder.PrependFloat32Slot(3, volume, 0.0)

def AddVolume(builder, volume):
    PositionAddVolume(builder, volume)

def PositionAddPrice(builder, price):
    builder.PrependFloat32Slot(4, price, 0.0)

def AddPrice(builder, price):
    PositionAddPrice(builder, price)

def PositionAddFrozen(builder, frozen):
    builder.PrependFloat32Slot(5, frozen, 0.0)

def AddFrozen(builder, frozen):
    PositionAddFrozen(builder, frozen)

def PositionAddPnl(builder, pnl):
    builder.PrependFloat32Slot(6, pnl, 0.0)

def AddPnl(builder, pnl):
    PositionAddPnl(builder, pnl)

def PositionAddTodayVolume(builder, todayVolume):
    builder.PrependFloat32Slot(7, todayVolume, 0.0)

def AddTodayVolume(builder, todayVolume):
    PositionAddTodayVolume(builder, todayVolume)

def PositionAddTodayPrice(builder, todayPrice):
    builder.PrependFloat32Slot(8, todayPrice, 0.0)

def AddTodayPrice(builder, todayPrice):
    PositionAddTodayPrice(builder, todayPrice)

def PositionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PositionEnd(builder)
