# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Tick(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Tick()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTick(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Tick
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Tick
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Tick
    def Exchange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Tick
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Tick
    def LastPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Tick
    def Amount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def OpenPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def HighPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def LowPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def ClosePrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def BidPrice(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tick
    def BidPriceAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Tick
    def BidPriceLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tick
    def BidPriceIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Tick
    def BidVolume(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tick
    def BidVolumeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tick
    def BidVolumeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tick
    def BidVolumeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Tick
    def AskPrice(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tick
    def AskPriceAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Tick
    def AskPriceLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tick
    def AskPriceIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # Tick
    def AskVolume(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tick
    def AskVolumeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tick
    def AskVolumeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tick
    def AskVolumeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

def TickStart(builder):
    builder.StartObject(14)

def Start(builder):
    TickStart(builder)

def TickAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    TickAddSymbol(builder, symbol)

def TickAddExchange(builder, exchange):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(exchange), 0)

def AddExchange(builder, exchange):
    TickAddExchange(builder, exchange)

def TickAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(2, timestamp, 0)

def AddTimestamp(builder, timestamp):
    TickAddTimestamp(builder, timestamp)

def TickAddLastPrice(builder, lastPrice):
    builder.PrependFloat32Slot(3, lastPrice, 0.0)

def AddLastPrice(builder, lastPrice):
    TickAddLastPrice(builder, lastPrice)

def TickAddVolume(builder, volume):
    builder.PrependInt32Slot(4, volume, 0)

def AddVolume(builder, volume):
    TickAddVolume(builder, volume)

def TickAddAmount(builder, amount):
    builder.PrependFloat32Slot(5, amount, 0.0)

def AddAmount(builder, amount):
    TickAddAmount(builder, amount)

def TickAddOpenPrice(builder, openPrice):
    builder.PrependFloat32Slot(6, openPrice, 0.0)

def AddOpenPrice(builder, openPrice):
    TickAddOpenPrice(builder, openPrice)

def TickAddHighPrice(builder, highPrice):
    builder.PrependFloat32Slot(7, highPrice, 0.0)

def AddHighPrice(builder, highPrice):
    TickAddHighPrice(builder, highPrice)

def TickAddLowPrice(builder, lowPrice):
    builder.PrependFloat32Slot(8, lowPrice, 0.0)

def AddLowPrice(builder, lowPrice):
    TickAddLowPrice(builder, lowPrice)

def TickAddClosePrice(builder, closePrice):
    builder.PrependFloat32Slot(9, closePrice, 0.0)

def AddClosePrice(builder, closePrice):
    TickAddClosePrice(builder, closePrice)

def TickAddBidPrice(builder, bidPrice):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(bidPrice), 0)

def AddBidPrice(builder, bidPrice):
    TickAddBidPrice(builder, bidPrice)

def TickStartBidPriceVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBidPriceVector(builder, numElems):
    return TickStartBidPriceVector(builder, numElems)

def TickAddBidVolume(builder, bidVolume):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(bidVolume), 0)

def AddBidVolume(builder, bidVolume):
    TickAddBidVolume(builder, bidVolume)

def TickStartBidVolumeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBidVolumeVector(builder, numElems):
    return TickStartBidVolumeVector(builder, numElems)

def TickAddAskPrice(builder, askPrice):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(askPrice), 0)

def AddAskPrice(builder, askPrice):
    TickAddAskPrice(builder, askPrice)

def TickStartAskPriceVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAskPriceVector(builder, numElems):
    return TickStartAskPriceVector(builder, numElems)

def TickAddAskVolume(builder, askVolume):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(askVolume), 0)

def AddAskVolume(builder, askVolume):
    TickAddAskVolume(builder, askVolume)

def TickStartAskVolumeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAskVolumeVector(builder, numElems):
    return TickStartAskVolumeVector(builder, numElems)

def TickEnd(builder):
    return builder.EndObject()

def End(builder):
    return TickEnd(builder)
